- src/main/java/com/soeasy/controller/customerController/CustomerController.java
- src/main/java/com/soeasy/model/CustomerBean.java
- src/main/webapp/fragment/header.jsp
修改controller 新增會員初始值
header.jsp新增導向
> Flanlove 2021-06-12

- src/main/webapp/WEB-INF/views/post/postByCategory.html
- src/main/webapp/WEB-INF/views/post/postIndex.jsp
- src/main/webapp/css/categoryNav.css
2.新增postBtCategory.jsp
3.更改postIndex.jsp
> 1.更改categoryNav.css

- src/main/java/com/soeasy/controller/sportmapController/SportMapController.java
- src/main/java/com/soeasy/service/sportmapService/SportMapService.java
- src/main/java/com/soeasy/service/sportmapService/impl/SportMapServiceImpl.java
- src/main/webapp/WEB-INF/views/sportMap/getAllSportMaps.jsp
- src/main/webapp/WEB-INF/views/sportMap/updateSportMap.jsp
2.新增jsp：updateSportMap(帶出單一頁面)
> 1.新增controller：從查詢所有的頁面點選查詢單一頁面

- src/main/java/com/soeasy/controller/nutritionistController/NutritionistIdController.java
- src/main/java/com/soeasy/model/NutritionistCategoryBean.java
- src/main/java/com/soeasy/repository/nutritionistRepository/NutritionistCategoryRepository.java
- src/main/java/com/soeasy/repository/nutritionistRepository/NutritionistRepository.java
- src/main/java/com/soeasy/service/nutritionistService/NutritionistCategoryService.java
- src/main/java/com/soeasy/service/nutritionistService/NutritionistService.java
- src/main/java/com/soeasy/service/nutritionistService/impl/NutritionistCategoryServiceImpl.java
- src/main/java/com/soeasy/service/nutritionistService/impl/NutritionistServiceImpl.java
- src/main/java/com/soeasy/util/GlobalService.java
> 1.Nutritionist後端程式CRUD(未完成)

- src/main/java/com/soeasy/controller/nutritionistController/NutritionistIdController.java
- src/main/java/com/soeasy/model/NutritionistBean.java
- src/main/java/com/soeasy/validator/nutritionistValidator/NutritionistValidator.java
- src/main/webapp/WEB-INF/views/nutritionist/addNutritionists.jsp
- src/main/webapp/WEB-INF/views/nutritionist/getAllNutritionists.jsp
- src/main/webapp/WEB-INF/views/nutritionist/nutritionistIndex.jsp
- src/main/webapp/fragment/footer.jsp
- src/main/webapp/fragment/header.jsp
> 1.新增addNutritionist.jsp、getAllNutritionist.jsp

- src/main/java/com/soeasy/controller/adminController/AdminLogin.java
- src/main/java/com/soeasy/service/mallService/MallPorductService.java
- src/main/java/com/soeasy/service/mallService/impl/MallproductServiceImpl.java
- src/main/java/com/soeasy/service/shopService/impl/ShopServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/adminIndex.jsp
- src/main/webapp/js/admin.js
> 2021-06-18

- src/main/java/com/soeasy/controller/adminController/AdminLogin.java
- src/main/java/com/soeasy/controller/adminController/AdminLoginInterceptor.java
- src/main/webapp/WEB-INF/views/customer/customerPage.jsp
- src/main/webapp/css/customerPage.css
> 2021-06-19

- src/main/java/com/soeasy/controller/customerController/CustomerController.java
- src/main/java/com/soeasy/service/customerService/impl/CustomerServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/admin/adminSportMap/adminSportMap.jsp
- src/main/webapp/WEB-INF/views/customer/customerPage.jsp
- src/main/webapp/css/customerPage.css
> 基本資料非同步修改完成

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminPost.java
- src/main/java/com/soeasy/model/PostBean.java
- src/main/java/com/soeasy/model/PostCategoryBean.java
- src/main/java/com/soeasy/model/PostUpdateBean.java
- src/main/java/com/soeasy/service/postService/impl/PostCategoryServiceImpl.java
- src/main/java/com/soeasy/validator/postValidator/PostUpdateBeanValidator.java
- src/main/webapp/WEB-INF/views/admin/adminPost/adminPost.jsp
- src/main/webapp/WEB-INF/views/admin/adminPost/adminPostUpdate.jsp
- src/main/webapp/WEB-INF/views/post/addPost.jsp
- src/main/webapp/WEB-INF/views/post/postByCategory.jsp
- src/main/webapp/css/admin.css
> 1.POST後臺CRUD完成

- src/main/java/com/soeasy/controller/customerController/CustomerController.java
- src/main/java/com/soeasy/controller/customerController/CustomerSignInController.java
- src/main/java/com/soeasy/controller/customerController/SignOutController.java
- src/main/java/com/soeasy/controller/shopController/ShopController.java
- src/main/java/com/soeasy/controller/shopController/ShopSignInController.java
- src/main/java/com/soeasy/model/member/ShopSignInBean.java
- src/main/java/com/soeasy/repository/shopRepository/ShopRepository.java
- src/main/java/com/soeasy/service/customerService/CustomerService.java
- src/main/java/com/soeasy/service/customerService/impl/CustomerServiceImpl.java
- src/main/java/com/soeasy/service/shopService/ShopService.java
- src/main/java/com/soeasy/service/shopService/impl/ShopServiceImpl.java
- src/main/java/com/soeasy/validator/shopValidator/ShopSignInValidator.java
- src/main/webapp/WEB-INF/views/customer/customerPage.jsp
- src/main/webapp/WEB-INF/views/customer/customerSignInUp.jsp
- src/main/webapp/WEB-INF/views/shop/shopSignInUp.jsp
- src/main/webapp/css/customerPage.css
- src/main/webapp/fragment/adminMenu.jsp
- src/main/webapp/fragment/customerMenu.jsp
- src/main/webapp/fragment/shopMenu.jsp
會員頁面健康資料表修改完成
廠商登入完成
會員頭像更新未完成
> 2021-06-22

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminCustomer.java
- src/main/java/com/soeasy/controller/customerController/CustomerController.java
- src/main/java/com/soeasy/repository/customerRepository/CustomerHealthRepository.java
- src/main/java/com/soeasy/repository/customerRepository/CustomerRepository.java
- src/main/java/com/soeasy/service/customerService/CustomerService.java
- src/main/java/com/soeasy/service/customerService/impl/CustomerServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
- src/main/webapp/css/admin.css
> 2021-06-25

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminProduct.java
- src/main/java/com/soeasy/controller/mallController/MallController.java
- src/main/java/com/soeasy/controller/mallController/MallProductController.java
- src/main/java/com/soeasy/controller/mallController/ProductCategoryController.java
- src/main/java/com/soeasy/model/ProductBean.java
- src/main/java/com/soeasy/model/ProductCategoryBean.java
- src/main/java/com/soeasy/repository/mallRepository/ProductCategoryRepository.java
- src/main/java/com/soeasy/repository/mallRepository/ProductRepository.java
- src/main/java/com/soeasy/service/mallService/ProductCategoryService.java
- src/main/java/com/soeasy/service/mallService/ProductService.java
- src/main/java/com/soeasy/service/mallService/impl/ProductCategoryImpl.java
- src/main/webapp/WEB-INF/views/mall/ProductCategory.jsp
- src/main/webapp/WEB-INF/views/mall/addProduct.jsp
- src/main/webapp/WEB-INF/views/mall/getOneProduct.jsp
- src/main/webapp/WEB-INF/views/mall/updateProduct.jsp
> 1.  修正分頁及按鈕

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminCustomer.java
- src/main/java/com/soeasy/model/CustomerBean.java
- src/main/java/com/soeasy/repository/customerRepository/CustomerRepository.java
- src/main/java/com/soeasy/service/customerService/CustomerService.java
- src/main/java/com/soeasy/service/customerService/impl/CustomerServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
> 2021-06-26

- src/main/webapp/WEB-INF/views/sportMap/getOneSportMap.jsp
> 2021-06-28

- src/main/java/com/soeasy/controller/recordController/RecordController.java
- src/main/java/com/soeasy/model/RecordBean.java
- src/main/webapp/WEB-INF/views/record/addRecord.jsp
2.getAllRecords.jsp(未完成)
3.reordIndex.jsp(未完成)
> 1.新增addRecord.jsp

- src/main/java/com/soeasy/config/WebAppConfig.java
- src/main/java/com/soeasy/controller/HomeController.java
- src/main/java/com/soeasy/controller/customerController/CustomerController.java
- src/main/java/com/soeasy/controller/customerController/CustomerSignInController.java
- src/main/java/com/soeasy/controller/customerController/CustomerSignInInterceptor.java
- src/main/java/com/soeasy/controller/shopController/ShopSignInInterceptor.java
- src/main/java/com/soeasy/controller/sportmapController/SportMapNeedLogin.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/sportMap/getOneSportMap.jsp
- src/main/webapp/css/admin.css
> 2021-06-30

- src/main/java/com/soeasy/controller/recordController/RecordController.java
- src/main/java/com/soeasy/model/RecordBean.java
- src/main/java/com/soeasy/repository/recordRepository/RecordRepository.java
- src/main/java/com/soeasy/service/recordService/RecordService.java
- src/main/java/com/soeasy/service/recordService/impl/RecordServiceImpl.java
- src/main/webapp/WEB-INF/views/nutritionist/getAllNutritionists.jsp
- src/main/webapp/WEB-INF/views/nutritionist/nutritionistIndex.jsp
- src/main/webapp/WEB-INF/views/record/addRecord.jsp
- src/main/webapp/WEB-INF/views/record/getAllRecords.jsp
2.getAllRecords.jsp(完成)
3.reordIndex.jsp(未完成)
> 1.新增addRecord.jsp(完成)

- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/admin/adminShop/adminShop.jsp
> 2021-07-01

- src/main/java/com/soeasy/controller/recordController/RecordController.java
- src/main/java/com/soeasy/repository/recordRepository/RecordRepository.java
- src/main/java/com/soeasy/service/nutritionistService/NutritionistService.java
- src/main/java/com/soeasy/service/nutritionistService/impl/NutritionistServiceImpl.java
- src/main/java/com/soeasy/service/recordService/RecordService.java
- src/main/java/com/soeasy/service/recordService/impl/RecordServiceImpl.java
- src/main/java/com/soeasy/util/GlobalService.java
- src/main/webapp/WEB-INF/views/nutritionist/getAllNutritionists.jsp
- src/main/webapp/WEB-INF/views/record/reordIndex.jsp
> 1. RecordController完成

- src/main/java/com/soeasy/controller/adminController/AdminLogin.java
- src/main/java/com/soeasy/controller/adminController/AdminLoginInterceptor.java
- src/main/java/com/soeasy/controller/adminController/adminManage/AdminShop.java
- src/main/java/com/soeasy/controller/shopController/ShopController.java
- src/main/java/com/soeasy/controller/shopController/ShopSignInController.java
- src/main/java/com/soeasy/service/shopService/ShopService.java
- src/main/java/com/soeasy/service/shopService/impl/ShopServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/admin/adminShop/adminShop.jsp
> 2021-07-02

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminCustomer.java
- src/main/java/com/soeasy/controller/adminController/adminManage/AdminShop.java
- src/main/java/com/soeasy/repository/shopRepository/ShopRepository.java
- src/main/java/com/soeasy/service/shopService/ShopService.java
- src/main/java/com/soeasy/service/shopService/impl/ShopServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminCustomer/adminCustomer.jsp
- src/main/webapp/WEB-INF/views/admin/adminPost/adminPost.jsp
- src/main/webapp/WEB-INF/views/admin/adminReply/adminReplyUpdate.jsp
- src/main/webapp/WEB-INF/views/admin/adminShop/adminShop.jsp
> 2021-07-03

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminLecturer.java
- src/main/java/com/soeasy/controller/lecturerController/LecturerController.java
- src/main/java/com/soeasy/model/LecturerBean.java
- src/main/java/com/soeasy/model/RecordBean.java
- src/main/java/com/soeasy/validator/lecturerValidator/LecturerBeanValidator.java
- src/main/java/com/soeasy/validator/mallValidator/ProductBeanValidator.java
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminLecture.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminAddLecturer.jsp
> 2021-07-05

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminLecture.java
- src/main/java/com/soeasy/repository/lectureRepository/LectureRepository.java
- src/main/java/com/soeasy/service/lectureService/impl/LectureServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminLecture.jsp
> 2021-07-07

- src/main/webapp/WEB-INF/views/nutritionist/getAllPageNutritionist.jsp
- src/main/webapp/WEB-INF/views/nutritionist/nutritionistIndex.jsp
- src/main/webapp/WEB-INF/views/record/getAllRecords.jsp
- src/main/webapp/WEB-INF/views/record/reordIndex.jsp
- src/main/webapp/fragment/customerMenu.jsp
> 1.reordIndex修改

- src/main/java/com/soeasy/controller/favoriteController/FavoriteController.java
- src/main/webapp/WEB-INF/views/customer/customerSignInUp.jsp
- src/main/webapp/WEB-INF/views/post/getOnePost.jsp
- src/main/webapp/fragment/customerMenu.jsp
> 1.新增按愛心加減積分

- src/main/java/com/soeasy/controller/passwordResetController/PasswordResetController.java
- src/main/java/com/soeasy/model/PasswordResetValidate.java
- src/main/webapp/WEB-INF/views/sportMap/sportMapIndex.jsp
> 2021-07-09

- src/main/java/com/soeasy/controller/nutritionistController/NutritionistIdController.java
- src/main/java/com/soeasy/controller/recordController/RecordController.java
- src/main/java/com/soeasy/service/nutritionistService/impl/NutritionistServiceImpl.java
- src/main/java/com/soeasy/service/recordService/RecordService.java
- src/main/java/com/soeasy/service/recordService/impl/RecordServiceImpl.java
- src/main/webapp/WEB-INF/views/nutritionist/getAllPageNutritionist.jsp
- src/main/webapp/WEB-INF/views/nutritionist/nutritionistIndex.jsp
- src/main/webapp/WEB-INF/views/record/reordIndex.jsp
- src/main/webapp/css/Record/record_index.css
- src/main/webapp/css/nutritionist/nutritionist_getAll.css
- src/main/webapp/css/nutritionist/nutritionist_index.css
> 1.Nutritionist亂數產生商品

- src/main/java/com/soeasy/controller/HomeController.java
- src/main/java/com/soeasy/controller/adminController/adminManage/AdminLecture.java
- src/main/java/com/soeasy/controller/lectureController/LectureController.java
- src/main/java/com/soeasy/model/LectureBean.java
- src/main/java/com/soeasy/repository/lectureRepository/LectureRepository.java
- src/main/java/com/soeasy/service/lectureService/impl/LectureServiceImpl.java
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminAddLecture.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminLecture.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminUpdateLecture.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminAddLecturer.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminLecturer.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminUpdateLecturer.jsp
- src/main/webapp/WEB-INF/views/lecture/getOneLecture.jsp
- src/main/webapp/css/lecture/lectureDetail.css
2. 講座前/後台新增地址/地圖。
3. 講座前台依照狀態、再透過講座日期排序。
> 1. 更改講師/講座後台資料較多欄位(input→textarea)。

- src/main/webapp/WEB-INF/views/adminIndex.jsp
- src/main/webapp/WEB-INF/views/post/addPost.jsp
- src/main/webapp/WEB-INF/views/post/deletePost.jsp
- src/main/webapp/WEB-INF/views/post/getOnePost.jsp
- src/main/webapp/WEB-INF/views/post/postByCategory.jsp
- src/main/webapp/WEB-INF/views/post/postByKeyword.jsp
- src/main/webapp/WEB-INF/views/post/postIndex.jsp
- src/main/webapp/WEB-INF/views/post/updatePost.jsp
> 1.把POST的JSP加上icon的css

- src/main/java/com/soeasy/controller/adminController/adminManage/AdminLecture.java
- src/main/java/com/soeasy/controller/adminController/adminManage/AdminLecturer.java
- src/main/webapp/WEB-INF/views/admin/adminLecture/adminLecture.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminAddLecturer.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminLecturer.jsp
- src/main/webapp/WEB-INF/views/admin/adminLecturer/adminUpdateLecturer.jsp
- src/main/webapp/WEB-INF/views/admin/adminPost/adminPostUpdate.jsp
- src/main/webapp/WEB-INF/views/lecture/archivedLectures.jsp
- src/main/webapp/WEB-INF/views/lecturer/lecturerIndex.jsp
- src/main/webapp/css/lecture/lectureIndex.css
- src/main/webapp/css/lecture/lecturer.css
- src/main/webapp/js/lecture/adminLecturer.js
> 更新講座/講師新增時的預設資料、
